export const INITIALIZE_ARTICLE_METADATA = 'INITIALIZE_ARTICLE_METADATA';
export type INITIALIZE_ARTICLE_METADATA = typeof INITIALIZE_ARTICLE_METADATA;

export const EXPAND_ARTICLE = 'EXPAND_ARTICLE';
export type EXPAND_ARTICLE = typeof EXPAND_ARTICLE;