export const EXPAND_ARTICLE = 'EXPAND_ARTICLE';
export type EXPAND_ARTICLE = typeof EXPAND_ARTICLE;

export const APPLY_SITE_LEVEL_CSS = 'APPLY_SITE_LEVEL_CSS';
export type APPLY_SITE_LEVEL_CSS = typeof APPLY_SITE_LEVEL_CSS;

export const APPLY_SITE_LEVEL_HTML = 'APPLY_SITE_LEVEL_HTML';
export type APPLY_SITE_LEVEL_HTML = typeof APPLY_SITE_LEVEL_HTML;

export const UPDATE_ARTICLE_CONTENT = 'UPDATE_ARTICLE_CONTENT';
export type UPDATE_ARTICLE_CONTENT = typeof UPDATE_ARTICLE_CONTENT;

export const UPDATE_SITE = 'UPDATE_SITE';
export type UPDATE_SITE = typeof UPDATE_SITE;

export const FOCUS_TAG = 'FOCUS_TAG';
export type FOCUS_TAG = typeof FOCUS_TAG;

export const SELECT_SECTION = 'SELECT_SECTION';
export type SELECT_SECTION = typeof SELECT_SECTION;

export const FOCUS_ARTICLE = 'FOCUS_ARTICLE';
export type FOCUS_ARTICLE = typeof FOCUS_ARTICLE;
