export const EXPAND_ARTICLE = 'EXPAND_ARTICLE';
export type EXPAND_ARTICLE = typeof EXPAND_ARTICLE;

export const UPDATE_ARTICLE_CONTENT = 'UPDATE_ARTICLE_CONTENT';
export type UPDATE_ARTICLE_CONTENT = typeof UPDATE_ARTICLE_CONTENT;

export const UPDATE_SITE = 'UPDATE_SITE';
export type UPDATE_SITE = typeof UPDATE_SITE;

export const FOCUS_TAG = 'FOCUS_TAG';
export type FOCUS_TAG = typeof FOCUS_TAG;
